services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${POSTGRES_PASSWORD:-passwd}
      PGUSER: ${POSTGRES_USER:-postgres}
      PARKING: True

  app:
    image: simple2b/svarog-app:latest
    restart: always
    command: sh ./start_web.sh
    environment:
      APP_ENV: production
      ALCHEMICAL_DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-passwd}@db:5432/db
    env_file:
      - .env
    depends_on:
      - db
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.svarog.rule=Host(`svarog.army`) || Host(`www.svarog.army`) || Host(`www.424bat.army`) || Host(`424bat.army`)'
      - 'traefik.http.routers.svarog.tls=true'
      - 'traefik.http.routers.svarog.tls.certresolver=myresolver'

volumes:
  db_data:
