services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${POSTGRES_PASSWORD:-passwd}
      PGUSER: ${POSTGRES_USER:-postgres}
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT:-15432}:5432

  app:
    build: .
    # restart: always
    command: sh ./start_web.sh
    environment:
      APP_ENV: production
      ALCHEMICAL_DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-passwd}@db:5432/db
    depends_on:
      - db
      - signal
    ports:
      - 127.0.0.1:${LOCAL_WEB_PORT:-8001}:8000

  signal:
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - MODE=json-rpc #supported modes: json-rpc, native, normal
      #- AUTO_RECEIVE_SCHEDULE=0 22 * * * #enable this parameter on demand (see description below)
    ports:
      - "8080:8080" #map docker port 8080 to host port 8080.
    volumes:
      - "./signal-cli-config:/home/.local/share/signal-cli" #map "signal-cli-config" folder on host system into docker container. the folder contains the password and cryptographic keys when a new number is registered


  # api:
  #   build: .
  #   # restart: always
  #   command: sh ./start_api.sh
  #   environment:
  #     APP_ENV: production
  #     IS_API: true
  #     ALCHEMICAL_DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-passwd}@db:5432/db
  #   depends_on:
  #     - db
  #   ports:
  #     - 127.0.0.1:${LOCAL_API_PORT:-8002}:8000

volumes:
  db_data:
