services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${POSTGRES_PASSWORD:-passwd}
      PGUSER: ${POSTGRES_USER:-postgres}
      PARKING: True

  app:
    image: simple2b/svarog-app:1
    restart: always
    command: sh ./start_web.sh
    environment:
      APP_ENV: production
      ALCHEMICAL_DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-passwd}@db:5432/db
    env_file:
      - .env
    depends_on:
      - db
      - signal
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.svarog_prod.rule=Host(`424bat.army`)'
      - 'traefik.http.routers.svarog_prod.tls=true'
      - 'traefik.http.routers.svarog_prod.tls.certresolver=myresolver'

  signal:
    image: bbernhard/signal-cli-rest-api:latest
    restart: always
    environment:
      - MODE=json-rpc #supported modes: json-rpc, native, normal
    volumes:
      - "./signal-cli-config:/home/.local/share/signal-cli"
volumes:
  db_data:
