"""add RecruitStatusChangeHistory

Revision ID: 336d9339831f
Revises: 3bf02da8cfc9
Create Date: 2024-12-30 22:15:38.271605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336d9339831f'
down_revision = '3bf02da8cfc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruit_status_change_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('recruit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recruit_id'], ['recruits.id'], name=op.f('fk_recruit_status_change_history_recruit_id_recruits')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recruit_status_change_history_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recruit_status_change_history'))
    )
    with op.batch_alter_table('recruit_status_change_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recruit_status_change_history_uuid'), ['uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruit_status_change_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recruit_status_change_history_uuid'))

    op.drop_table('recruit_status_change_history')
    # ### end Alembic commands ###
