"""fix recruit

Revision ID: 376b027e96f2
Revises: 737c1eff1807
Create Date: 2024-09-28 10:18:58.363938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '376b027e96f2'
down_revision = '737c1eff1807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruits', schema=None) as batch_op:
        batch_op.alter_column('birth_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('education',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('skills',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('health_problems',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('have_driver_license',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('uav_experience',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruits', schema=None) as batch_op:
        batch_op.alter_column('uav_experience',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.alter_column('have_driver_license',
               existing_type=sa.String(length=64),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
        batch_op.alter_column('health_problems',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.alter_column('skills',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.alter_column('education',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    # ### end Alembic commands ###
