"""non_unique_application_phone

Revision ID: 3bf02da8cfc9
Revises: 5b00b770d4f0
Create Date: 2024-10-03 10:21:06.628710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf02da8cfc9'
down_revision = '5b00b770d4f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint('uq_applications_phone', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_applications_phone', ['phone'])

    # ### end Alembic commands ###
