"""add RecruitStatusChangeEvent

Revision ID: 411c64501483
Revises: 336d9339831f
Create Date: 2025-01-02 11:05:41.862406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '411c64501483'
down_revision = '336d9339831f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruit_status_change_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('recruit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recruit_id'], ['recruits.id'], name=op.f('fk_recruit_status_change_events_recruit_id_recruits')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recruit_status_change_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recruit_status_change_events'))
    )
    with op.batch_alter_table('recruit_status_change_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recruit_status_change_events_uuid'), ['uuid'], unique=False)

    with op.batch_alter_table('recruit_status_change_history', schema=None) as batch_op:
        batch_op.drop_index('ix_recruit_status_change_history_uuid')

    op.drop_table('recruit_status_change_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruit_status_change_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('recruit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recruit_id'], ['recruits.id'], name='fk_recruit_status_change_history_recruit_id_recruits'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_recruit_status_change_history_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_recruit_status_change_history')
    )
    with op.batch_alter_table('recruit_status_change_history', schema=None) as batch_op:
        batch_op.create_index('ix_recruit_status_change_history_uuid', ['uuid'], unique=False)

    with op.batch_alter_table('recruit_status_change_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recruit_status_change_events_uuid'))

    op.drop_table('recruit_status_change_events')
    # ### end Alembic commands ###
