"""recruit comments

Revision ID: 59e4d381c334
Revises: 0d7ac9cdce2b
Create Date: 2024-10-01 17:34:13.199930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e4d381c334'
down_revision = '0d7ac9cdce2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.Text(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruits', schema=None) as batch_op:
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
