"""spec name ua-en

Revision ID: 5b00b770d4f0
Revises: 0d7ac9cdce2b
Create Date: 2024-10-03 10:19:30.895491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b00b770d4f0'
down_revision = '0d7ac9cdce2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.String(length=64), server_default='None', nullable=False))
        batch_op.add_column(sa.Column('name_uk', sa.String(length=64), server_default='Нема', nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.drop_column('name_uk')
        batch_op.drop_column('name_en')

    # ### end Alembic commands ###
