"""in Specialty add is_active

Revision ID: 5dd67e4f653a
Revises: 3bf02da8cfc9
Create Date: 2025-01-05 23:18:23.214437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd67e4f653a'
down_revision = '3bf02da8cfc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
