"""recruit_application

Revision ID: 788d3ab11748
Revises: e750c1bf6cfa
Create Date: 2024-09-30 12:46:40.529141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788d3ab11748'
down_revision = 'e750c1bf6cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('city_of_actual_residence', sa.String(length=64), nullable=False),
    sa.Column('education', sa.Text(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=False),
    sa.Column('last_job', sa.String(length=64), nullable=False),
    sa.Column('health_problems', sa.Text(), nullable=False),
    sa.Column('have_driver_license', sa.String(length=64), nullable=False),
    sa.Column('is_serviceman', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('uav_experience', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'IN_PROGRESS', 'REJECTED', 'HIRED', name='recruitstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recruits')),
    sa.UniqueConstraint('phone', name=op.f('uq_recruits_phone'))
    )
    with op.batch_alter_table('recruits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recruits_uuid'), ['uuid'], unique=False)

    op.create_table('specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialties'))
    )
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_specialties_uuid'), ['uuid'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('city_of_actual_residence', sa.String(length=64), nullable=False),
    sa.Column('education', sa.Text(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=False),
    sa.Column('last_job', sa.String(length=64), nullable=False),
    sa.Column('health_problems', sa.Text(), nullable=False),
    sa.Column('have_driver_license', sa.String(length=64), nullable=False),
    sa.Column('is_serviceman', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('uav_experience', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('recruit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recruit_id'], ['recruits.id'], name=op.f('fk_applications_recruit_id_recruits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('phone', name=op.f('uq_applications_phone'))
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_uuid'), ['uuid'], unique=False)

    op.create_table('application_specialty',
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('specialty_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_specialty_application_id_applications')),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], name=op.f('fk_application_specialty_specialty_id_specialties'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    op.drop_table('application_specialty')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_uuid'))

    op.drop_table('applications')
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_specialties_uuid'))

    op.drop_table('specialties')
    with op.batch_alter_table('recruits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recruits_uuid'))

    op.drop_table('recruits')
    # ### end Alembic commands ###
