"""stats

Revision ID: a07548aac042
Revises: 89c3410b5d6d
Create Date: 2025-07-27 15:25:36.893919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07548aac042'
down_revision = '89c3410b5d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tanks', sa.Integer(), nullable=True),
    sa.Column('mlrss', sa.Integer(), nullable=True),
    sa.Column('spas', sa.Integer(), nullable=True),
    sa.Column('afvs', sa.Integer(), nullable=True),
    sa.Column('cars', sa.Integer(), nullable=True),
    sa.Column('motorcycles', sa.Integer(), nullable=True),
    sa.Column('buggies', sa.Integer(), nullable=True),
    sa.Column('rofs', sa.Integer(), nullable=True),
    sa.Column('guns', sa.Integer(), nullable=True),
    sa.Column('mortars', sa.Integer(), nullable=True),
    sa.Column('adss', sa.Integer(), nullable=True),
    sa.Column('radars', sa.Integer(), nullable=True),
    sa.Column('ammos', sa.Integer(), nullable=True),
    sa.Column('shelters', sa.Integer(), nullable=True),
    sa.Column('uavs', sa.Integer(), nullable=True),
    sa.Column('antennas', sa.Integer(), nullable=True),
    sa.Column('other', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_day_stats')),
    sa.UniqueConstraint('day', name=op.f('uq_day_stats_day'))
    )
    with op.batch_alter_table('day_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_day_stats_uuid'), ['uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_day_stats_uuid'))

    op.drop_table('day_stats')
    # ### end Alembic commands ###
