"""custom_links

Revision ID: c2381cb4625f
Revises: 69587990eb60
Create Date: 2025-11-17 20:23:29.878873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2381cb4625f'
down_revision = '69587990eb60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=32), nullable=False),
    sa.Column('link_url', sa.String(length=256), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_links'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_links')
    # ### end Alembic commands ###
