"""rec_comments

Revision ID: d9cfbd8b5491
Revises: 3bf02da8cfc9
Create Date: 2024-10-08 08:55:28.732838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9cfbd8b5491'
down_revision = '3bf02da8cfc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.Text(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruits', schema=None) as batch_op:
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
