name: Prod build and deploy

on:
  release:
    types:
      - released

env:
  DOCKER_LOGIN: simple2b
  IMAGE_NAME: simple2b/svarog-app
  DEPLOY_HOST: ${{ secrets.SSH_HOST_IP_PROD }}
  DEPLOY_USER_NAME: ${{ secrets.SSH_USER_PROD }}
  DEPLOY_SSH_KEY: ${{ secrets.SSH_KEY_PROD }}
  DEPLOY_SSH_PORT: ${{ secrets.SSH_PORT_PROD }}
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}


jobs:
  deploy:
    name: Deploy to prod
    runs-on: Linux
    steps:
      - uses: actions/checkout@v3
      - name: update compose file
        uses: appleboy/scp-action@v0.1.4
        with:
          # change to peod envs
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER_NAME }}
          key: ${{ env.DEPLOY_SSH_KEY }}
          port: ${{ env.DEPLOY_SSH_PORT }}
          source: "compose.prod.yaml,set_image_version.sh"
          target: ~/svarog_prod
      - name: deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER_NAME }}
          key: ${{ env.DEPLOY_SSH_KEY }}
          port: ${{ env.DEPLOY_SSH_PORT }}
          script: |
            cd ~/svarog_prod &&
            mv compose.prod.yaml compose.yaml &&
            ./set_image_version.sh ${{github.ref_name}} &&
            docker-compose pull &&
            docker-compose up -d &&
            docker system prune -f
