# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test backend

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  test:
    name: Test
    runs-on: Linux
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install pipx
        run: pip install --user pipx

      - name: Add pipx to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.5.16"
      - name: Install dependencies
        working-directory: .
        run: |
          uv sync
      - name: Lint with ruff
        working-directory: .
        run: |
          uv run ruff check .
          uv run ruff format --check .
      - name: Run mypy
        working-directory: .
        run: |
          uv run mypy
      - name: Run pytest
        working-directory: .
        run: |
          uv run pytest test_flask
          uv run pytest test_api
